### ISSUE TITLE
Ball catching

### ISSUE THREAD

**Issue by xenoner1506** [ZhumaevaVika/Lesson_1#5]
- "import *" запрещенная конструкция.
- Много глобальных переменных (в идеале их не должно быть), которые могут быть просто переменными.
- Капсом называют константы, но в даном случае понятен мотив.
- Местами можно использовать распаковку, чтобы адекватно обозначить переменные.

**Comment by ZhumaevaVika** [comment]
work - код до рефакторинга, osu - полностью рабочий вариант
Капс убрала, глобальные переменные уже лень переделывать(
